name: Build pc-ble-driver-py
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
        include:
          - python-version: '3.7'
            toxpy: py37
          - python-version: '3.8'
            toxpy: py38
          - python-version: '3.9'
            toxpy: py39
          - python-version: '3.10'
            toxpy: py310
          - python-version: '3.11'
            toxpy: py311
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: pc-ble-driver-py

    - name: Checkout pc-ble-driver
      uses: actions/checkout@v3
      with:
        repository: NordicSemiconductor/pc-ble-driver
        ref: c0ffd419053e2405fffdb02ce7f1f9acceff4a66
        path: pc-ble-driver
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential libspdlog-dev libasio-dev libudev-dev

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: toxify
      working-directory: pc-ble-driver
      run: |
         python -m pip install scikit-build tox
         tox -e ${{ matrix.toxpy }}
        
    - name: Compile pc-ble-driver
      working-directory: pc-ble-driver
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_TESTS=1 -DNRF_BLE_DRIVER_VERSION=4.1.100 -G "Unix Makefiles" ..
        make nrf_ble_driver_sd_api_v5_static
        sudo make install

    - name: Build pc-ble-driver-py wheels
      working-directory: pc-ble-driver-py
      run: |
        python setup.py bdist_wheel --build-type Release
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pc_ble_driver_py-linux-${{ matrix.os }}-${{ matrix.toxpy}}
        path: "pc-ble-driver-py/dist/*.whl"
        if-no-files-found: error
